---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ghcr.io/randsw/k8s-cnpg:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: app-user-creds
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-user-creds
              key: password
        - name: POSTGRESQL_URL
          value: my-postgres-cluster-rw
        - name: POSTGRESQL_URL_R
          value: my-postgres-cluster-ro
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: app
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app.kind.cluster
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-app-service
            port:
              number: 80
